title: "Bellabeat Project"
description: "Bellabeat, a high-tech company producing smart health-focused products, believes that analyzing smart device fitness data could help unlock new growth opportunities for the company. I did that task in this project by analyzing data collected from Fitbit fitness trackers and coming up with some insights and actionable recommendations."
baseurl: ""
url: "https://humannguyen.github.io/my_portfolio"
